

# ====== Configuration

# --- Model
model.type: 'Equiv' # 'NoPhysicsGnn'      # used by train.GNN
model.name: 'Equiv_GIN_KNN5'     # used as wandb group for bookkeeping
model.desc: "sanity check after code refactorization"

# --- Dataset
dataset.name: "CoordToCnc_KNN5"           # used to retrieve path to data
dataset.in_memory: true                   # whether to load all the data in RAM, passed to PatientDataset
dataset.num_node_features: 0              # zero if no WSS values
dataset.num_graph_features: 3             # one-hot encoded LAD, LCX, RCA

# --- Cross val
cv.valid_ratio: None                      # not applicable
cv.k_fold: 10
cv.fold_id: None                          # not applicable
cv.seed: 0

# ====== Hyperparameters

# --- Architecture
num_gin: 0
num_equiv: 3
num_hidden_dim: 8

# --- Optimizer
optimizer.name: "Adam"
optimizer.lr: 0.0001
optimizer.momentum: 0.0

# --- Loss
loss.weight: 0.6

# --- Training
batch_size: 16
epochs: 700
early_stop: 100
allow_stop: 100

# ---
physics: 0

