

# WARNING: activate the conda environment on the workers before running the agent

# Wandb sweep configuration for coarse hyperparameter tuning.
# The search method is Bayesian and we only use train/val split, i.e. no KFoldCV.

# ====== Sweep-specific configuration
program: run_sweep.py       # script to run
method: bayes                      # method to go over hyperparams
description: "gin only"
metric:                           # reference metric, must be logged at top level
  name: val_f1_score
  goal: maximize

parameters:
  # ====== Model configuration, see config.yaml

  # --- Model
  model.type:
    value: "GIN"
  model.name:
    value: "GIN_rot"
  model.desc:
    value: "GIN only model"

  # --- Dataset
  dataset.name:
    value: "CoordToCnc_rot"
  dataset.in_memory:
    value: true
  dataset.num_node_features:
    value: 0
  dataset.num_graph_features:
    value: 3

  # --- Cross val
  cv.valid_ratio:
    value: 0.25
  cv.k_fold:
    value: None
  cv.fold_id:
    value: None
  cv.seed:
    value: 0

  # ====== Actual hyperparameters

  # --- Architecture
  num_gin:
    distribution: int_uniform
    min: 1
    max: 7

  num_hidden_dim:
    values:
      - 8
      - 12
      - 16

  # --- Optimizer
  optimizer.name:
    value: "Adam"

  optimizer.lr:
    distribution: log_uniform
    min: -9.21034
    max: -4.605170185988091

  optimizer.momentum:
    value: 0.0

  # --- Loss
  loss.weight:
    distribution: uniform
    min: 0.6
    max: 0.85

  # --- Training
  batch_size:
    value: 12
  epochs:
    distribution: int_uniform
    min: 60
    max: 400

  early_stop:
    value: 100

  allow_stop:
    value: 100

  # ---
  physics:
    value: 0

