description: "PerimToTsvi+Cnc"
method: grid
parameters:
  allow_stop:
    value: 1000
  batch_size:
    value: 12
  cv.fold_id:
    values:
    - 0
    - 1
    - 2
    - 3
    - 4
  cv.k_fold:
    value: 5
  cv.seed:
    value: 0
  cv.valid_ratio:
    value: None
  dataset.in_memory:
    value: true
  dataset.name:
    value: "PerimToTsvi+Cnc"
  dataset.num_graph_features:
    value: 3
  dataset.num_node_features:
    value: 1
  dataset.standardize:
    value: "standardize"
  early_stop:
    value: 1000
  epochs:
    values:
    - 70
    - 100
  loss.weight:
    values:
    - 0.57
  model.desc:
    value: ""
  model.name:
    value: EGNN
  model.type:
    value: Equiv
  model.aux_task:
    value: true
  model.aux_loss_weight:
    values:
      - 2e-1
      - 1e-3
  num_equiv:
    values:
    - 3
    - 5
  num_gin:
    values:
      - 0
      - 1
  num_hidden_dim:
    values:
    - 5
    - 8
  optimizer.lr:
    values:
    - 1e-3
  optimizer.momentum:
    value: 0
  optimizer.name:
    value: Adam
  physics:
    value: 0
program: run_sweep_kfold.py
