

# WARNING: activate the conda environment on the workers before running the agent

# Wandb sweep configuration for coarse hyperparameter tuning.
# The search method is Bayesian and we only use train/val split, i.e. no KFoldCV.

# ====== Sweep-specific configuration
program: run_sweep.py       # script to run
method: bayes                      # method to go over hyperparams
description: "CoordToCnc with master node + batch norm"
metric:                           # reference metric, must be logged at top level
  name: val_f1_score
  goal: maximize

parameters:
  # ====== Model configuration, see config.yaml

  # --- Model
  model.type:
    value: "EquivMastered"
  model.name:
    value: "EGNN_GIN_KNN5"
  model.desc:
    value: ""

  # --- Dataset
  dataset.name:
    value: "CoordToCnc"
  dataset.in_memory:
    value: true
  dataset.num_node_features:
    value: 0
  dataset.num_graph_features:
    value: 3

  # --- Cross val
  cv.valid_ratio:
    value: 0.25     # not applicable for kfold
  cv.k_fold:
    value: None
  cv.fold_id:
    value: None
  cv.seed:
    value: 0

  # ====== Actual hyperparameters

  # --- Architecture
  num_gin:
    values:
      - 0
      - 1

  num_equiv:
    distribution: int_uniform
    min: 2
    max: 6

  num_hidden_dim:
    values:
      - 5
      - 8
      - 12
      - 16

  # --- Optimizer
  optimizer.name:
    value: "Adam"

  optimizer.lr:
    distribution: log_uniform
    max: -4.605170185988091
    min: -9.210340371976182

  optimizer.momentum:
    value: 0.0

  # --- Loss
  loss.weight:
    distribution: uniform
    min: 0.4
    max: 0.75

  # --- Training
  batch_size:
    value: 12
  epochs:
    distribution: int_uniform
    min: 60
    max: 250

  early_stop:
    value: 1000

  allow_stop:
    value: 1000

  # ---
  physics:
    value: 0

